### ISSUE TITLE
Alt + Backspace doesn't work correctly on command line

### ISSUE THREAD

**Issue by dgelessus** [ywangd/stash#92] opened 2015-02-01 00:53 UTC
When using Alt + Backspace to delete an entire word at once on the command line, the word appears to be deleted correctly, but upon pressing Enter it reappears in its former location. This seems to happen consistently no matter if any text is entered, deleted or otherwise modified after using alt-backspace, and the reappearing text doesn't overwrite any of the new input.

**Comment by ywangd** [comment] 2015-02-01 11:48
@dgelessus I can reproduce this issue. Thanks for reporting it. I'll take a closer look when I have some more time.

**Comment by ywangd** [comment] 2015-02-02 11:57
This issue is more or less caused by a bug or incompleteness of the UI system. Alt + Backspace does NOT trigger `textview_should_change` event despite it does delete a word... It does however trigger a `textview_did_change_selection` event due to the cursor movement. 

I can possibly make a quick fix to do some text check in `textview_did_change_selection`. But it feels like a bandaid solution to me. I'd like to have a proper fix for this. So I'll need some time to look at the whole handling of input buffer. Currently, the read and write are done to an output buffer and flush to the screen instead of working directly with the screen text. But maybe the input part should be faithful to whatever the screen actually displays.

**Comment by ywangd** [comment] 2015-02-03 00:42
Ok, I think a proper fix is NOT possible without fixing the bug of Pythonista UI system first. Because it bypasses the `textview_should_change` event, ALT+Delete will happily delete beyond the read position, i.e. it can delete the prompt, which is impossible otherwise. Another key-combo that has similar issue is `Ctrl-K` which is the Forward word deletion (opposite to Alt+Delete). I can put up a bandaid fix to it. But it probably won't catch all scenarios. This really should be reported back to omz.

**Comment by ywangd** [comment] 2015-02-03 11:28
The fix is now pushed with 5f19acd5ad930bf8cf04cfe0ea6d9f02a4d66060
Please let me know how it works for you.

**Closed** 2015-08-03 01:09 UTC
